### PR TITLE
minimum 2.6.9

### PR DESCRIPTION
**Pull request by ThaDafinser**
You need to use at least 2.6.9 version

Otherwise this error will appear:
https://travis-ci.org/ThaDafinser/UserAgentParser/jobs/114478151#L291

### CODE REVIEW

**Comment by jenssegers** [comment]
Could you use `^2.6.8` instead? :)

**Comment by ThaDafinser** [comment]
@jenssegers changed to your prefered version contraint.

Yes the `prefer-lowest` is sometimes really helpful

**Comment by jenssegers** [comment]
Oh wait, it should have been `^2.6.9` no?

**Comment by ThaDafinser** [comment]
Damm yeah...just copied your contraint without thinking
It was '>2.6.8' https://github.com/ThaDafinser/agent/commit/b5380127635080953e103fa09587df07aba72cc8

**Comment by jenssegers** [comment]
Looks like this version is still failing though: https://travis-ci.org/jenssegers/agent/jobs/114512804

**Comment by ThaDafinser** [comment]
@jenssegers seems like in my abstraction that part/method was never called.

But it's a good thing, that this error is now detected :+1: 

Do you have a follow up PR for that?

**Comment by jenssegers** [comment]
2.7.6 should do it.

**Pull request merged**
