### PR TITLE
create mac address function

### PR DESCRIPTION
**Pull request by karim-khan**
this function work get client MAC address by a access on a website or project.
This function call $agent->macAddress();

This function add Agent.php and this function simple call $agent->macAddress(); it show mack address for client . it is 100% work i check .
please check and add this code .

this code is ok then functon write read me file 

$agent->macAddress();

Thanks
karim

### CODE REVIEW

**Comment by ThaDafinser** [comment]
@karim-khan i don't believe that this code works 100% :wink: 

Platform = client
ipconfig/ifconfig = server

I believe in your case, that you used your server as a client, that's why it kinda "worked"

**Comment by karim-khan** [comment]
ok i check this picture 
mac_address

**Comment by karim-khan** [comment]
ipconfig/all only use windows and ifcongif -a use Linux or Ubuntu or OS

**Comment by jenssegers** [comment]
This is indeed the server's up address. This also somewhat out of the scope of this package.

**Comment by karim-khan** [comment]
its ok all right good luck

**Pull request closed without merging**
