### PR TITLE
Add further patterns to robots array

### PR DESCRIPTION
**Pull request by williamgb**
Furthermore, Agent::$robots is now a list, the associative array didn't seem necessary(?). Credit due to https://github.com/monperrus/crawler-user-agents for the data.

### CODE REVIEW

**Comment by ThatTomPerson** [comment]
Twitterbot and SimpleCrawler are repeated

**Comment by earnaway** [comment]
Any reason why this PR was never pulled in or used? Just be really handy to have a more extensive list for robot detection?
Thanks!

**Comment by earnaway** [comment]
Sorry to hassle again, but wondering if @jenssegers has had a chance to look at this and thoughts on getting it merged in?

**Comment by jenssegers** [comment]
The latest version is now using jaybizzle/crawler-detect to do better robot detection.

**Pull request closed without merging**
